---
title: "About"
---

## Background
Originally from Lagos, Nigeria, I’ve always been driven by a strong curiosity for tech and problem-solving. Over the past five years, I’ve built a solid foundation across technical support, IT coordination, and research following my degree in Information Science and Media Studies. Today, I’m building on that experience as a Master of Data Science student at UBC!

## Why Data Science
My interest in Data Science was sparked during my undergraduate studies, where I first discovered how powerful data-driven decision-making can be. The field naturally brought together the exact skills, analytical thinking, and areas of knowledge I was eager to explore. Choosing to pursue it further was a seamless blend of my background and core professional curiosity.

## Outside of Data Science
When I’m not diving into data, you’ll usually find me baking up something delicious, picking up my guitar, or lost in a great book. I also love a good game, whether on a screen or a board. These creative outlets keep me balanced, inspired, and always curious.